#!/usr/bin/env python3
from ev3dev2.button import Button
from ev3dev2.sound import Sound

btn = Button()
sound = Sound()

while True:
  print("i'm looping")
  if btn.any():#checks if any button is pressed.
    print("button pressed")
    sound.beep()#wait for the beep to finish.
    exit()#Stop the program
else:
  print("i'm sleeping")
  sleep(0.01)#wait 0.01 second

btn.wait_for_bump('left')
sound.beep()
btn.wait_for_pressed(['up', 'down'])
sound.beep()
btn.wait_for-released('right')
sound.beep()
Sound.play_song((
('E4', 'D4'),
('C4', 'D4'),
('E4', 'E4'),
('E4', 'D4'),
('D4', 'D4'),
('E4', 'E4'),
('E4', 'E4'),
('D4', 'C4'),
('D4', 'E4'),
('E4', 'E4').
('D4', 'D4'),
('E4', 'D4'),
('C4', 'C4'),
('C4')
)
